server:
  port: 8083

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/customer-master-changelog.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true